# Generated by Django 4.2.7 on 2023-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_name', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Oil Paint', 'Oil Paint'), ('Cement Paint', 'Cement Paint'), ('Distemper Paint', 'Distemper Paint'), ('Emulsion Paint', 'Emulsion Paint'), ('Whitewash', 'Whitewash'), ('Enamel Paint', 'Enamel Paint'), ('Acrylic Emulsion Paint', 'Acrylic Emulsion Paint'), ('Bituminous Paint', 'Bituminous Paint'), ('Synthetic Rubber Paint', 'Synthetic Rubber Paint'), ('Anti-Corrosion Paint', 'Anti-Corrosion Paint')], max_length=100)),
                ('Brand', models.CharField(choices=[('Asian Paints', 'Asian Paints'), ('Berger Paints', 'Berger Paints'), ('Kansai Nerolac Paints', 'Kansai Nerolac Paints'), ('AkzoNobel India', 'AkzoNobel India'), ('Indigo Paints', 'Indigo Paints'), ('Nippon Paints', 'Nippon Paints'), ('Shalimar Paints', 'Shalimar Paints'), ('Dulux Paints', 'Dulux Paints'), ('Jenson & Nicholson Paints', 'Jenson & Nicholson Paints'), ('Sheenlac Paints', 'Sheenlac Paints')], max_length=100)),
                ('Color_code', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'product',
            },
        ),
    ]
