# Generated by Django 4.2.7 on 2023-12-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_options_product_alert_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.CharField(choices=[('Asian Paints', 'Asian Paints'), ('Berger Paints', 'Berger Paints'), ('Kansai Nerolac Paints', 'Kansai Nerolac Paints'), ('AkzoNobel India', 'AkzoNobel India'), ('Indigo Paints', 'Indigo Paints'), ('Nippon Paints', 'Nippon Paints'), ('Shalimar Paints', 'Shalimar Paints'), ('Dulux Paints', 'Dulux Paints'), ('Jenson & Nicholson Paints', 'Jenson & Nicholson Paints'), ('Sheenlac Paints', 'Sheenlac Paints')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
