# Generated by Django 4.2.7 on 2023-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_product_brand_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('Oil Paint', 'Oil Paint'), ('Cement Paint', 'Cement Paint'), ('Distemper Paint', 'Distemper Paint'), ('Emulsion Paint', 'Emulsion Paint'), ('Whitewash', 'Whitewash'), ('Enamel Paint', 'Enamel Paint'), ('Acrylic Emulsion Paint', 'Acrylic Emulsion Paint'), ('Bituminous Paint', 'Bituminous Paint'), ('Synthetic Rubber Paint', 'Synthetic Rubber Paint'), ('Anti-Corrosion Paint', 'Anti-Corrosion Paint')], max_length=100),
        ),
    ]
